<?xml version="1.0" encoding="GB2312"?> 

<?xml-stylesheet type="text/xsl" href="students.xsl"?>

<!DOCTYPE students[
<!ELEMENT students (student+)>
<!ELEMENT student (name,age,score)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT score (#PCDATA)>
<!ATTLIST student sn CDATA #REQUIRED>
]>

<students>
    <student sn="01">
        <name>张三</name>
        <age>18</age>
    </student>
    
    <student sn="02">
        <name>李四</name>
        <age>20</age>
    </student>
</students>